[package]
name = "unique_kmer_counter"
version = "0.2.0"
edition = "2021"

authors = [
	"Pierre Peterlongo <pierre.peterlongo@inria.fr>",
	]

[dependencies]
flate2 = "1.0"
clap = "4"
dashmap = "6"
rayon = "1.5"
# File parsing
fxread           = { version = "0.2.14" }